
/**
 * DATA CONFIGURATION
 * The audio files are expected to be in the 'audio/' folder.
 * Filenames should be the lowercase version of the word (e.g., "applaud" -> "audio/applaud.mp3").
 */
export const WORD_LIST = [
  { word: "APPLAUD" },
  { word: "MYTH" },
  { word: "LIFEGUARD" },
  { word: "GOVERNMENT" },
  { word: "LIBRARIES" },
  { word: "HEADACHE" },
  { word: "IMPOSSIBLE" },
  { word: "CONTINUE" },
  { word: "LANGUAGE" },
  { word: "DEFINITION" },
  { word: "WHISPERING" },
  { word: "PARAGRAPH" },
  { word: "INTERPRET" },
  { word: "VULNERABLE" },
  { word: "UNBELIEVABLE" },
  { word: "ACHIEVED" },
  { word: "POPULATION" },
  { word: "TSUNAMI" },
  { word: "SIGNATURE" },
  { word: "ANALYZE" },
  { word: "SYNONYMS" },
  { word: "EARTHQUAKE" },
  { word: "INCREASE" },
  { word: "ENTERTAIN" },
  { word: "SQUEEZE" },
  { word: "WINDSHIELD" },
  { word: "TONGUE" },
  { word: "MIGHTY" },
  { word: "THUNDERSTORM" },
  { word: "SLIPPERY" },
  { word: "SPLURGE" },
  { word: "SCARECROW" },
  { word: "PROGRESSIVE" },
  { word: "MULTIPLY" },
  { word: "BLOSSOM" },
  { word: "WORRIED" },
  { word: "SACRIFICE" },
  { word: "FREIGHT" },
  { word: "CREATURES" },
  { word: "STRENGTH" },
  { word: "ECLIPSE" },
  { word: "DISTANCE" },
  { word: "SURVIVORS" },
  { word: "SCISSORS" },
  { word: "DOUBTFUL" },
  { word: "CLIMAX" },
  { word: "DIALOGUE" },
  { word: "EXERCISE" },
  { word: "STUBBORN" },
  { word: "TRACKSUIT" },
  { word: "ENTERTAINMENT" },
  { word: "EQUIPMENT" },
  { word: "EXPERIENCE" },
  { word: "PREFERABLE" },
  { word: "TELEVISION" },
  { word: "CELEBRATION" },
  { word: "HUMOROUS" },
  { word: "EXCLAMATION" },
  { word: "IGNORANT" },
  { word: "MEASUREMENT" },
  { word: "REQUIREMENT" },
  { word: "DEFINITELY" },
  { word: "INDEPENDENCE" },
  { word: "IMMIGRANT" },
  { word: "INCREDIBLE" },
  { word: "COMMUNICATION" },
  { word: "WHISTLING" },
  { word: "EMBARRASSING" },
  { word: "ANXIOUS" },
  { word: "TECHNOLOGY" },
  { word: "METROPOLITAN" },
  { word: "MILLIONAIRE" },
  { word: "CHARACTERIZATION" },
  { word: "ANNOUNCEMENT" },
  { word: "LEADERSHIP" },
  { word: "EXPRESSION" },
  { word: "NEIGHBORHOOD" },
  { word: "SCIENTIFIC" },
  { word: "THROUGHOUT" },
  { word: "CONDENSATION" },
  { word: "MEANWHILE" },
  { word: "UNFORGETTABLE" },
  { word: "TRIUMPH" },
  { word: "EXPENSIVE" },
  { word: "APPEARANCE" },
  { word: "POLITELY" },
  { word: "SHIPWRECK" },
  { word: "INGREDIENT" },
  { word: "HERITAGE" },
  { word: "MONUMENTS" },
  { word: "DISCIPLINE" },
  { word: "HURRICANE" },
  { word: "INTELLIGENT" },
  { word: "LIGHTNING" },
  { word: "COMPETITION" },
  { word: "PRIVILEGE" },
  { word: "CURRICULUM" },
  { word: "ELECTRICITY" },
  { word: "PERSONALITY" },
  { word: "SPECIALIZATION" }
];

export const EXTRA_LETTERS_COUNT = 5;
export const CELEBRATION_DELAY = 2000;
